### ISSUE TITLE
1) In memory sessions; and 2) user log out

### ISSUE THREAD

**Issue by adam-hanna** [RichardKnop/go-oauth2-server#27]
Hi Richard,

First, great library. I've been exploring it for the past few days and I really like it. Thanks for the great work!

Second, two quick questions:

1. You're storing configs in etcd or consul, but it appears that sessions are being stored in memory `s.session.Values`? Any reason you chose not to store sessions in etcd or consul?
2. When a user logs out, you clear the sessions. However, any access / refresh tokens granted on the user's behalf are not affected. This means that anyone with an auth token can continue making requests on the user's behalf. I understand that it's outside of oAuth 2.0's scope to define sessions / what happens when a user logs out but what are your thoughts on how log out should affect tokens? Maybe both access and refresh tokens should be revoked? Or maybe there should be a check against user session when a token is being refreshed?

Cheers!

**Comment by liviuignat** [comment]
Hi Adam,

Etcd and consul are made for storing sessions. Something like `redis` is more appropriate.

When a user logs out you should:
- kill the session.
- revoke all tokens used from that client.

**Comment by adam-hanna** [comment]
> Etcd and consul are not made for storing sessions. Something like redis is more appropriate.

Interesting, thanks for letting me know. I have very little experience with key value stores. I might play around with redis and try integrating it into this repo.

> When a user logs out you should:
> 
> - kill the session.
> - revoke all tokens used from that client.

Totally agree. Essentially, a call to revoke tokens for that client needs to be added:

```go
// session/service.go
// ClearUserSession deletes the user session
func (s *Service) ClearUserSession() error {
	// Make sure StartSession has been called
	if s.session == nil {
		return ErrSessonNotStarted
	}

	// Delete the user session
	delete(s.session.Values, UserSessionKey)

	// ADD CODE HERE TO DELETE ALL TOKENS?

	return s.session.Save(s.r, s.w)
}
```

**Comment by RichardKnop** [comment]
@adam-hanna Hi and thanks for the comments.

1) You are right that the current way sessions are not handled in a very robust way. Basically the sessions storage is only needed for the log in form when users go to the authorization page and it was not part of the spec so I just implemented it in the simplest way, storing sessions in memory.

I guess the proper way would be to have a persistent session storage. Probably the Postgres database would be good place to store sessions rather than etcd. Usually I have seen people store sessions in database (Postgres or MySQL) or something like Redis. I haven't seen etcd being used to store sessions before but I guess technically you could do that.

2) I agree. The whole session functionality has been done in very simplistic way to save time. When user logs out, any access / refresh tokens should be deleted from database.

**Comment by liviuignat** [comment]
PS: Google and other big OAuth2 providers are having and endpoint to logout. Like `[GET] /dialog/logout?redirect_uri={someurl}`.

This will clear the SSO Provider session and redirect you to a new url. This has to be called by the web client after your client revoked all the tokens, so you make sure that you are logged out also from the SSO, otherwise only your client will be logged out, but if the SSO still has a session and you can easily get another.

**Comment by RichardKnop** [comment]
In theory if you log out, both access token (in 1 hour) and refresh token (in 2 weeks) will expiry. 

But yes, obviously the tokens should be deleted for security reasons.

**Comment by adam-hanna** [comment]
@RichardKnop 
> If you want to create a PR to fix this, feel free to do it. I might eventually come around and fix this myself but I will be quite busy for next couple of months so it might take me a long time.

Excellent, working on one now! :)

**Comment by PumpkinSeed** [comment]
@RichardKnop _"refresh token (in 2 weeks) will expiry"_

That's right but the refresh token should be alive for a really long time. Currently we are using the modified version of your library, and we setted the expire time for 2 year. For example the Google doing the same, because this is the functionality of the refresh token. This is why we created the same endpoint for the logout. I saw @adam-hanna started to working on it.

@liviuignat _"and endpoint to logout"_
The logout endpoint what you mentioned can be ugly. For example, what happen whan you have a mobile app and the user want to logout. We created the logout endpoint which handle the logout in the background as an AJAX request. But I totally agree with you about the endpoint.

@RichardKnop _" Probably the Postgres database would be good "_

Yes it can be, but you have to keep in mind not everybody use Postgres, so something else could be better for that. We solved is with Redis and if I will have sparetime I colud have create a PR for that, because how I saw at my last PR there was a refactor on the library and our version is modified in a lots of area. 

I really want to contribute to this library for say thanx, because it saved for me a lots of time.

**Comment by RichardKnop** [comment]
@PumpkinSeed The way it works is refresh token lifetime gets extended every time you use the access token. So if you keep making regular API requests with access token (for example, mobile app), it will never expire. See here:

https://github.com/RichardKnop/go-oauth2-server/blob/master/oauth/authenticate.go#L35

Every time `Authenticate` is called it extends the expiration date of refresh token.

So it will only expire after two weeks of inactivity from user (user doesn't open the mobile app for 2 weeks).

But it is driven by configuration so you can edit the config, increase this value

https://github.com/RichardKnop/go-oauth2-server/blob/master/config/config.go#L18
