### ISSUE TITLE
combine efforts with Dex project?

### ISSUE THREAD

**Issue by philips** [RichardKnop/go-oauth2-server#4]
Hello Richard-

I can't find your email so I am filing an issue.

Is there a reason you are building this project instead of using Dex: github.com/coreos/dex? I noticed this project started recently so maybe you didn't stumble upon Dex.

Dex implements OAUTH2.0 and OpenID connect and I have started integrating it and testing it against different projects like Kubernetes and Bitly's oauth2_proxy project.

Cheers,

Brandon
brandon@coreos.com

cc @bobbyrullo

**Comment by RichardKnop** [comment]
@philips 

Hi Brandon,

You are right, I haven't stumbled upon Dex. It looks interesting.

I am starting a new job soon and as a first engineer I will be helping bootstrap a very early stage startup, building a B2B REST API. I will write the API in Go and I needed some sort of standard authorisation mechanism for the new platform I will build. 

OAuth 2.0 seemed like the way to go which is why I created this project, in hopes it could possibly be reused by other people building B2B REST APIs.

I will take a look at Dex to see what the differences are and perhaps I can use it instead.

Regards,

Richard

**Comment by bobbyrullo** [comment]
@RichardKnop - Did you mean authentication (instead of authorization)? If you really did mean authz, what kind of requirements were you thinking?

Also - even if you don't end up working with dex (I hope you do!) you should consider OpenID Connect instead of OAuth2  - it's almost as easy to implement but *so* much better

**Comment by philips** [comment]
@RichardKnop Would love to do a hangout sometime soon about soon or chat in #dex in https://coreos-community.herokuapp.com

**Comment by RichardKnop** [comment]
@bobbyrullo Yes I meant authentication. Basically we are building a REST API plus a white label platform as a first client of the platform but we will have other businesses integrate their websites / mobile apps with our API.

Why is OpenID Connect better?

@philips Yes, perhaps we could have a chat.

**Comment by bobbyrullo** [comment]
OpenID Connect *is* essentially OAuth2 but with a bunch of stuff that is vague or unspecified in the OAuth2 Spec made explicit. For example: how do you get information about a user once you've done the token exchange? Every OAuth2 provider does it differently, which means provider specific logic in each OAuth2 client. In OIDC, the token you get back from the provider is actually deserializable into a set of claims about the user, instead of just being an opaque string.
